<?php
/**
 * @file
 * antiquessites_events.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function antiquessites_events_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_talk_image_hide_on_page'.
  $field_bases['field_talk_image_hide_on_page'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_talk_image_hide_on_page',
    'field_permissions' => array(
      'type' => 0,
    ),
    'global_block_settings' => 1,
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        0 => '',
        1 => '',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_boolean',
  );

  // Exported field_base: 'field_type_of_event'.
  $field_bases['field_type_of_event'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_type_of_event',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        1 => 'HIGHLIGHTS TOURS',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
