<?php
/**
* @name logoblock.module
* @author Giovanni Capuano <giovanni.capuano@clarionevents.com>
* @version 1.0
*  
* @file
* Implements various blocks to improve pending content workflow.
*/

/**
* Implements hook_block_info().
*/
function buytickets_block_info() {
	$blocks['buytickets_block'] = array(
		'info' => t('Buy Tickets Block'),
		'status' => TRUE,
		'region' => 'content',
		'weight' => -13,
		'visibility' => 1,
		'class' => array(
			'buytickets-block'
      	), 
	);
	return $blocks;
}


/**
* Implements hook_block_configure().
*/
function buytickets_block_configure($delta) {
	$form = array();
	switch($delta) {
	case 'buytickets_block':

      $form['seetickets_london'] = array(
          '#type' => 'textfield',
          '#title' => t('Link seeTickets for <strong style="color:red">Destinations London</strong>'),
          '#size' => 20,
          '#maxlength' => 255,
          '#default_value' => variable_get('link_seetickets_london', ''),
      );

        // File selection form element
        $form['banner_file_london'] = array(
            '#name' => 'block_image_london',
            '#type' => 'managed_file',
            '#title' => t('Destination London - Choose an Image File'),
            '#description' => t('Select an Image for the <strong>London</strong> custom block.  Only *.gif, *.png, *.jpg, and *.jpeg images allowed.'),
            '#default_value' => variable_get('block_image_fid_london', ''),
            '#upload_location' => 'public://block_image/',
            '#upload_validators' => array(
                'file_validate_extensions' => array('gif png jpg jpeg'),
            ),
        );


        $form['seetickets_manchester'] = array(
          '#type' => 'textfield',
          '#title' => t('Link seeTickets for <strong style="color:red">Destinations Manchester</strong>'),
          '#size' => 20,
          '#maxlength' => 255,
          '#default_value' => variable_get('link_seetickets_manchester', ''),
      );

        // File selection form element
        $form['banner_file_manchester'] = array(
            '#name' => 'block_image_manchester',
            '#type' => 'managed_file',
            '#title' => t('Destination Manchester - Choose an Image File'),
            '#description' => t('Select an Image for the <strong>Manchester</strong> custom block.  Only *.gif, *.png, *.jpg, and *.jpeg images allowed.'),
            '#default_value' => variable_get('block_image_fid_manchester', ''),
            '#upload_location' => 'public://block_image/',
            '#upload_validators' => array(
                'file_validate_extensions' => array('gif png jpg jpeg'),
            ),
        );
	  
	  break;
	}
	return $form;
}



/**
 * Implements hook_block_save().
 */
function buytickets_block_save($delta = '', $edit = array()) {
  switch($delta) {
    case 'buytickets_block' :

      variable_set('link_seetickets_manchester', $edit['seetickets_manchester']);
      variable_set('link_seetickets_london', $edit['seetickets_london']);

        // Saving the file, setting it to a permanent state, setting a FID variable
        $file_london = file_load($edit['banner_file_london']);
        $file_london->status = FILE_STATUS_PERMANENT;
        file_save($file_london);
        $block_london = block_load('buytickets', $delta);
        file_usage_add($file_london, 'buytickets', 'block', $block_london->bid);
        variable_set('block_image_fid_london', $file_london->fid);




        // Saving the file, setting it to a permanent state, setting a FID variable
        $file_manchester = file_load($edit['banner_file_manchester']);
        $file_manchester->status = FILE_STATUS_PERMANENT;
        file_save($file_manchester);
        $block_manchester = block_load('buytickets', $delta);
        file_usage_add($file_manchester, 'buytickets', 'block', $block_manchester->bid);
        variable_set('block_image_fid_manchester', $file_manchester->fid);


        break;
  }
  
  return;
}


/**
 * Implements hook_block_view().
 */
function buytickets_block_view($delta='') {
  $block = array();
  drupal_add_js();
  
  switch($delta) {
    case 'buytickets_block' :
      $block['content'] = displaybuyticketsblock_block_view();
      break;
  }
  
  return $block;
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return returns a renderable array of block content.
 */
function displaybuyticketsblock_block_view() {
  $block = array();

global $user;
  $user = user_load($user->uid); // Make sure the user object is fully loaded
  $field_event = field_get_items('user', $user, 'field_event');
  $output = field_view_value('user', $user, 'field_event', $field_event[0]);
   
  if($output['#title'] == "London"){
    $link_view = variable_get('link_seetickets_london', '');
    $image_file = file_load(variable_get('block_image_fid_london', ''));
  }else{
    $link_view = variable_get('link_seetickets_manchester', '');
  	$image_file = file_load(variable_get('block_image_fid_manchester', ''));
  }
  
  
   // Capture the image file path and form into HTML with attributes
 
  $image_path = '';

  if (isset($image_file->uri)) {
    $image_path = $image_file->uri;
  }

  $image = theme_image(array(
    'path' => ($image_path),
    'alt' => t('Destination logo'),
    'title' => t('Destinations show'),
    'attributes' => array('class' => 'destination-logo'),
  ));

  // Block output in HTML with div wrapper
  $block = array(
    
    'flipDate' => array(
      '#type' => 'markup',
      '#markup' => '<div class="logo-image"><a href="' . $link_view . '" target="_blank">' . $image . '</a></div><h3>Book your tickets today</h3><a class="discover-button" href="' . $link_view .'" target="_blank">Buy tickets<i class="fa fa-angle-right"></i></a>',
      '#suffix' => '',
    )
  );

  return $block;
}